### PR TITLE
fix: Update Vanilla OS logo

### PR DESCRIPTION
**Pull request by jardon**
- Replace Vanilla OS logo
- Update gresource xml file for svg
- Update README screenshot

### CODE REVIEW

**Comment by mirkobrombin** [comment]
I think the logo is too big

**Comment by jardon** [comment]
It's more in line with the slides after it, but I can shrink it some

**Comment by jardon** [comment]
Any thoughts now that I made it smaller? @mirkobrombin @kbdharun

**Comment by mirkobrombin** [comment]
I would make it a little smaller, at least 30px less in proportion, then in my opinion it's perfect

**Comment by jardon** [comment]
done and done

**Review by mirkobrombin — APPROVED** [review]

**Pull request merged**
